#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GOAL: Calculate a list of TOTAL secondary current powers generated by each
dipole in a list of primary current dipoles, for every subject with a
converted volume conductor (convert_fem_mat_to_vc.py's output).

Must be run with a Python 3.8 interpreter matching the duneuropy.so build
(e.g. /usr/bin/python3.8) -- this is the only stage of the pipeline with
that constraint; everything else runs under a normal python3.
"""
import glob
import os
import sys
import time
from multiprocessing import Pool

import numpy as np
import pandas as pd

DUNEUROPY_PATH = '/home/bic/vikramn/build-release/duneuro-py/src/'
sys.path.append(DUNEUROPY_PATH)
import duneuropy as dp  # noqa: E402  (path must be extended first)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
VC_DIR = os.path.join(SCRIPT_DIR, '..', 'outputs', 'secondary_p', 'vc_3layer')
VERTICES_DIR = os.path.join(SCRIPT_DIR, '..', 'outputs')
IDIP_RMS_DIR = os.path.join(SCRIPT_DIR, '..', 'outputs', 'primary_p', 'idip_rms')
OUTPUT_DIR = os.path.join(SCRIPT_DIR, '..', 'outputs', 'secondary_p', 'fem_p_rms')

# SnrFixed value of the primary-power pipeline to pair against -- 3 is the
# value used throughout the rest of this codebase as the default/reported
# SNR (see compare_pri_sec_dip_p.m, plot_total_p_histogram.py).
SNR = 3

# Each worker keeps its own MEEGDriver3d alive across every dipole it's
# handed instead of rebuilding one per dipole: driver construction re-reads
# and re-assembles the subject's whole FEM mesh (~285k tetrahedra) and takes
# several seconds, while a single forward solve with an already-built driver
# takes well under a second. Rebuilding per dipole (the previous behavior)
# multiplied that assembly cost by ~15,000x per subject.
#
# SECONDARY_P_N_WORKERS overrides the default -- e.g. when running several
# subjects concurrently as separate OS processes (each pinned to one
# subject via SECONDARY_P_SUBJECTS), set it low enough per-process that the
# concurrent processes' worker counts sum to about os.cpu_count() instead
# of each independently trying to grab 20 cores.
N_WORKERS = int(os.environ.get('SECONDARY_P_N_WORKERS', min(20, os.cpu_count() or 1)))

# partial_integration is the deliberate choice for THIS (secondary-P power
# dissipation) computation -- not the same problem as Brainstorm's own
# forward modeling, which used venant for the Gain matrix/MNE source
# localization (confirmed from headmodel_surf_duneuro.mat History fields
# across all 30 subjects: "Fem source model: venant, type : fitted, cg").
# That venant config is captured below for reference/completeness (Brainstorm's
# own defaults: numberOfMoments=3, referenceLength=20, weightingExponent=1,
# relaxationFactor=1e-6, mixedMoments=true, restrict=true,
# initialization='closest_vertex'), but partial_integration is what this
# pipeline actually uses -- justify that choice in the manuscript methods
# rather than switching to match the (different-purpose) primary-P pipeline.
SOURCE_MODEL = 'partial_integration'
SOURCE_MODEL_CONFIGS = {
    'partial_integration': {'type': 'partial_integration'},
    'venant': {
        'type': 'venant',
        'numberOfMoments': 3,
        'referenceLength': 20,
        'weightingExponent': 1,
        'relaxationFactor': 1e-6,
        'mixedMoments': True,
        'restrict': True,
        'initialization': 'closest_vertex',
    },
    'subtraction': {
        'type': 'subtraction',
        'intorderadd': 0,
        'intorderadd_lb': 0,
    },
    'localized_subtraction': {
        'type': 'localized_subtraction',
        'restrict': False,
        'initialization': 'single_element',
        'intorderadd_eeg_patch': 0,
        'intorderadd_eeg_boundary': 0,
        'intorderadd_eeg_transition': 0,
        'extensions': 'vertex vertex',
    },
}

_worker_driver = None
_worker_driver_cfg = None


def _init_worker(driver_cfg):
    global _worker_driver, _worker_driver_cfg
    _worker_driver_cfg = driver_cfg
    _worker_driver = dp.MEEGDriver3d(driver_cfg)


def _solve_dipole(position_and_moment):
    position, moment = position_and_moment
    dipole = dp.Dipole3d(position, moment)
    solution_storage = _worker_driver.makeDomainFunction()
    _worker_driver.solveEEGForward(dipole, solution_storage, _worker_driver_cfg)
    # integral of <sigma * grad u, grad u> over the head volume
    return _worker_driver.computePower(solution_storage)


def build_driver_cfg(vc_data, source_model):
    # nodes/elements/labels/conductivities MUST be plain Python lists here,
    # not numpy arrays: passing numpy arrays (even int64/float64, matching
    # dtypes) through pybind11 into MEEGDriver3d silently builds a corrupted
    # grid -- every dipole then fails to locate its containing element
    # ("coordinate is outside of the grid, or grid is not convex") even
    # though the same coordinates independently verified as correctly
    # inside a valid, non-degenerate element of that mesh. Plain nested
    # Python lists/ints/floats avoid whatever conversion path causes this.
    mesh_cfg = {
        'nodes': vc_data['nodes'].tolist(),
        'elements': [[int(v) for v in row] for row in vc_data['elements']],
    }
    tensor_cfg = {
        'labels': [int(v) for v in vc_data['labels']],
        'conductivities': [float(v) for v in vc_data['conductivities']],
    }
    driver_cfg = {
        'type': 'fitted',
        'solver_type': 'cg',
        'element_type': 'tetrahedron',
        'post_process': 'true',
        'subtract_mean': 'true',
        'volume_conductor': {'grid': mesh_cfg, 'tensors': tensor_cfg},
        'solver': {
            'reduction': '1e-10',  # matches Brainstorm's own duneuro_defaults.m SolSolverReduction default
            'edge_norm_type': 'houston',
            'penalty': '20',
            'scheme': 'sipg',
            'weights': 'tensorOnly',
        },
        'source_model': SOURCE_MODEL_CONFIGS[source_model],
    }
    return driver_cfg


def find_subjects():
    # SECONDARY_P_SUBJECTS=sub-0002,sub-0008 restricts which subjects a run
    # processes (e.g. for a quick single-subject pipeline validation)
    # without needing a separate code path -- unset, every subject with the
    # required inputs on disk is processed.
    only = os.environ.get('SECONDARY_P_SUBJECTS')
    only = set(only.split(',')) if only else None

    subjects = []
    for vc_file in sorted(glob.glob(os.path.join(VC_DIR, 'sub-*_vc_3layer.npz'))):
        subject = os.path.basename(vc_file)[:-len('_vc_3layer.npz')]
        if only is not None and subject not in only:
            continue
        vertices_file = os.path.join(VERTICES_DIR, f'{subject}_vertices.csv')
        idip_file = os.path.join(IDIP_RMS_DIR, f'{subject}_snr{SNR}_idip_rms.csv')
        if os.path.exists(vertices_file) and os.path.exists(idip_file):
            subjects.append(subject)
        else:
            print(f'Skipping {subject}: missing {vertices_file} and/or {idip_file}.')
    return subjects


def process_subject(subject):
    out_file = os.path.join(OUTPUT_DIR, f'{subject}_snr{SNR}_fem_p_rms.csv')
    if os.path.exists(out_file):
        print(f'Skipping {subject}: {out_file} already exists.')
        return

    print(f'=== {subject}: loading inputs ===')
    vc_data = np.load(os.path.join(VC_DIR, f'{subject}_vc_3layer.npz'))
    dipole_positions = np.array(pd.read_csv(
        os.path.join(VERTICES_DIR, f'{subject}_vertices.csv'), header=None))
    dipole_moments = np.array(pd.read_csv(
        os.path.join(IDIP_RMS_DIR, f'{subject}_snr{SNR}_idip_rms.csv'), header=None))
    if len(dipole_positions) != len(dipole_moments):
        raise ValueError(
            f'{subject}: {len(dipole_positions)} dipole positions vs. '
            f'{len(dipole_moments)} dipole moments -- must match.')

    driver_cfg = build_driver_cfg(vc_data, SOURCE_MODEL)
    args = list(zip(dipole_positions.tolist(), dipole_moments.tolist()))

    print(f'{subject}: solving {len(args)} dipoles with {N_WORKERS} workers...')
    start = time.perf_counter()
    with Pool(N_WORKERS, initializer=_init_worker, initargs=(driver_cfg,)) as pool:
        powers = pool.map(_solve_dipole, args)
    elapsed = time.perf_counter() - start
    print(f'{subject}: done in {elapsed:.1f}s ({elapsed / len(args) * 1000:.1f} ms/dipole)')

    pd.DataFrame(np.array(powers)).to_csv(out_file, header=False, index=False)
    print(f'  wrote {out_file}')


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    subject_list = find_subjects()
    if not subject_list:
        raise FileNotFoundError(
            f'No subject has both a volume conductor in {VC_DIR} and '
            f'matching vertices/idip_rms inputs -- run convert_fem_mat_to_vc.py first.')

    print(f'Found {len(subject_list)} subject(s) ready to run: {subject_list}')
    for subject in subject_list:
        process_subject(subject)


if __name__ == '__main__':
    main()
