% Script generated by Brainstorm (21-Jun-2023)

% Input files
sFiles = [];
SubjectNames = { ...
    'sub-0002', 'sub-0008', 'sub-0009', 'sub-0010', ...
    'sub-0011', 'sub-0012', 'sub-0014', 'sub-0015', ...
    'sub-0016', 'sub-0018', 'sub-0019', 'sub-0020', ...
    'sub-0021', 'sub-0022', 'sub-0023', 'sub-0024', 'sub-0025', ...
    'sub-0026', 'sub-0028', 'sub-0029', 'sub-0030', 'sub-0031', ...
    'sub-0032', 'sub-0033', 'sub-0034', 'sub-0035', 'sub-0036', ...
    'sub-0037', 'sub-0039', 'sub-0040', 'sub-0041', ...
};
ProtocolName = 'OmegaSubset';

% Make sure brainstorm3 is on the path: a fresh headless MATLAB session
% (e.g. launched by run_batch_cat12.sh) does not have it by default.
if ~exist('brainstorm', 'file')
    addpath('/export02/data/vikramn/brainstorm3');
end

% Start Brainstorm headless if it isn't already running (server mode fully
% disables GUI popups, so this also runs fine unattended with no display).
% If Brainstorm is already open (e.g. running this interactively from the
% GUI), this is a no-op and the already-loaded protocol/session is reused.
if ~brainstorm('status')
    brainstorm server
end
iProtocol = bst_get('Protocol', ProtocolName);
if isempty(iProtocol)
    error('Protocol "%s" not found in the current Brainstorm database.', ProtocolName);
end
gui_brainstorm('SetCurrentProtocol', iProtocol);

% CAT12 (26.0.rc1+) renames its own folder under spm12/toolbox between
% "cat12" and "CAT" as part of its version bookkeeping, and Brainstorm's own
% plugin-linking recreates the other name alongside it -- this happens on
% EVERY bst_plugin('Install','cat12',...) call, i.e. once per subject, not
% just once per script run. If both CAT/ and cat12/ exist at once (as
% symlinks to the same target), SPM's toolbox scan (spm_jobman('initcfg') ->
% spm_cfg.m) registers CAT12 twice in the same session, which hangs
% deterministically -- this caused two separate real multi-hour stalls,
% diagnosed 2026-07-27. dedupeCat12Link() (defined at the end of this file)
% must therefore be called before EVERY subject, not just once up front.
dedupeCat12Link();

% Start a new report
bst_report('Start', sFiles);

% CAT12 is registered with Version='latest' and AutoUpdate=1, so Brainstorm
% treats it as different from the online version on every single call and
% reinstalls (redownloads + recompiles + rescans the whole toolbox) every
% time -- which is what caused multi-hour stalls during process_segment_cat12.
% Disable auto-updates so an already-installed plugin is reused as-is.
bst_set('AutoUpdates', 0);
% AutoUpdates=0 alone does not stop bst_plugin('Install', ...) from still
% making an online "check latest version" request (bst_plugin.m>GetVersionOnline)
% on every single call -- that request itself is what was hanging for a long
% time. Force isInternet off so it's skipped entirely: CAT12/SPM12 are
% already installed, so no plugin needs to reach the network in this script.
global GlobalData;
GlobalData.Program.isInternet = 0;

% Skip subjects that already have completed CAT12 results in the current
% protocol, so reruns don't re-segment (and don't hit the "subject already
% exists" database warning) for subjects that are already done.
ProtocolInfo = bst_get('ProtocolInfo');

% Process: Segment MRI with CAT12
for i=1:numel(SubjectNames)
    existing = dir(fullfile(ProtocolInfo.STUDIES, SubjectNames{i}, 'CAT12', ...
        'results_surface_thickness_*.mat'));
    if ~isempty(existing)
        fprintf('Skipping %s: CAT12 results already exist.\n', SubjectNames{i});
        continue;
    end

    % Must run before EVERY subject: see the dedupeCat12Link() comment above.
    dedupeCat12Link();

    sFiles = bst_process('CallProcess', 'process_segment_cat12', sFiles, [], ...
        'subjectname', SubjectNames{i}, ...
        'nvertices',   15000, ...
        'tpmnii',      {'', 'Nifti1'}, ...
        'sphreg',      1, ...
        'vol',         0, ... % Volume ROI atlases: not needed for cortical thickness, biggest memory/time cost
        'extramaps',   1, ... %%make sure this is 1!!
        'cerebellum',  0);

    % Save report (skip 'Open': it pops a GUI viewer, which is both
    % unnecessary and unsafe to call in an unattended/headless run)
    ReportFile = bst_report('Save', sFiles);
    bst_report('Export', ReportFile, '/export02/data/vikramn/brainstorm3/reports/');
    % bst_report('Email', ReportFile, username, to, subject, isFullReport);
    
    % Delete temporary files
    % gui_brainstorm('EmptyTempFolder');
end


% ===== LOCAL FUNCTIONS =====
function dedupeCat12Link()
    SpmToolboxDir = fullfile(bst_get('UserPluginsDir'), 'spm12', 'spm12', 'toolbox');
    CatLink   = fullfile(SpmToolboxDir, 'CAT');
    Cat12Link = fullfile(SpmToolboxDir, 'cat12');
    if ~(exist(CatLink, 'dir') && exist(Cat12Link, 'dir'))
        return;
    end
    [~, catTarget]   = system(['readlink -f ''' CatLink '''']);
    [~, cat12Target] = system(['readlink -f ''' Cat12Link '''']);
    if ~isequal(strtrim(catTarget), strtrim(cat12Target))
        % Different targets: something unexpected, don't touch it automatically.
        error(['Both "%s" and "%s" exist and point to different targets.' 10 ...
               'Resolve this manually before running CAT12.'], CatLink, Cat12Link);
    end
    fprintf('BST> Removing duplicate CAT12 toolbox link "%s" (kept "%s") to avoid a double-registration hang.\n', CatLink, Cat12Link);
    % Plain `rm` (no -r): only removes a symlink entry, refuses outright on a
    % real directory -- so this can't accidentally delete real plugin files
    % even if CatLink somehow isn't a symlink.
    [rmStatus, rmMsg] = system(['rm ''' CatLink '''']);
    if rmStatus ~= 0
        error('Failed to remove duplicate link %s: %s', CatLink, rmMsg);
    end
end

